- name: Deploy to App Engine
  uses: google-github-actions/deploy-appengine@v0.4.0

  with:
    project: ${{ secrets.gcp_project }}
    deliverables: ../../app.yaml
    credentials: ${{ secrets.gcp_credentials }}