name: Express Continous Integration

on:
  push:
    branches: [ main ]

jobs:
  install-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -y


